services:
  gpt-codegen-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt-codegen-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gptcodegen
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - ollama
    networks:
      - internal

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gptcodegen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - internal
    command: serve

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  ollama_models:
